first_name = input("First name: ")
last_name = input("Last name: ")
phone_number = input("Phone number: ")
print("\n")
print(f"""Your register name is {first_name} {last_name}.""")
print("Your phone number is " + phone_number + ".")
